import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { BusinessProfile, Entity, Transaction } from "./types";
import type { EntityBalance } from "./selectors";
import { formatRupeesPlain } from "./format";

const BRAND = "#4F46E5";
const INK = "#16171d";
const MUTED = "#6b7280";
const MINT = "#16a34a";
const ROSE = "#e11d48";

export function buildStatementPdf(
  entity: Entity,
  transactions: Transaction[],
  balance: EntityBalance,
  business: BusinessProfile
): Blob {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // --- Header ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(BRAND);
  doc.text("HISAB", margin, 52);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(business.name, margin, 68);

  doc.setFontSize(9);
  doc.text(
    `Generated ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}`,
    pageWidth - margin,
    52,
    { align: "right" }
  );

  doc.setDrawColor(230);
  doc.line(margin, 82, pageWidth - margin, 82);

  // --- Account block ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(INK);
  doc.text(`Account Statement — ${entity.name}`, margin, 112);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  const metaLine = [entity.relationship, entity.phone].filter(Boolean).join("  ·  ");
  if (metaLine) doc.text(metaLine, margin, 128);

  const period =
    transactions.length > 0
      ? `${new Date(transactions[transactions.length - 1].createdAt).toLocaleDateString("en-IN")} – ${new Date(
          transactions[0].createdAt
        ).toLocaleDateString("en-IN")}`
      : "No transactions";
  doc.text(`Statement period: ${period}`, margin, 142);

  // --- Table ---
  const rows = transactions.map((t) => [
    new Date(t.createdAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }),
    t.direction === "incoming" ? `You got from ${entity.name}` : `You gave to ${entity.name}`,
    PAYMENT_LABELS[t.paymentMethod] ?? t.paymentMethod,
    `${t.direction === "incoming" ? "+" : "-"}${formatRupeesPlain(t.amount)}`,
  ]);

  autoTable(doc, {
    startY: 160,
    margin: { left: margin, right: margin },
    head: [["Date", "Description", "Payment", "Amount"]],
    body: rows,
    styles: { font: "helvetica", fontSize: 9.5, textColor: INK, cellPadding: 6 },
    headStyles: { fillColor: BRAND, textColor: "#ffffff", fontStyle: "bold" },
    alternateRowStyles: { fillColor: "#f8f8fb" },
    columnStyles: { 3: { halign: "right", fontStyle: "bold" } },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 3) {
        const raw = rows[data.row.index][3];
        data.cell.styles.textColor = raw.startsWith("+") ? MINT : ROSE;
      }
    },
  });

  // --- Summary ---
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY ?? 160;
  const summaryY = finalY + 30;
  const boxWidth = 220;
  const boxX = pageWidth - margin - boxWidth;

  doc.setDrawColor(230);
  doc.setFillColor(248, 248, 251);
  doc.roundedRect(boxX, summaryY, boxWidth, 92, 6, 6, "FD");

  doc.setFontSize(9.5);
  doc.setTextColor(MUTED);
  doc.text("You gave", boxX + 14, summaryY + 22);
  doc.text("You got", boxX + 14, summaryY + 40);

  doc.setTextColor(INK);
  doc.setFont("helvetica", "bold");
  doc.text(formatRupeesPlain(balance.totalGiven), boxX + boxWidth - 14, summaryY + 22, { align: "right" });
  doc.text(formatRupeesPlain(balance.totalGot), boxX + boxWidth - 14, summaryY + 40, { align: "right" });

  doc.setDrawColor(230);
  doc.line(boxX + 14, summaryY + 52, boxX + boxWidth - 14, summaryY + 52);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text("Balance", boxX + 14, summaryY + 72);
  doc.setTextColor(balance.label === "They owe you" ? MINT : INK);
  doc.text(formatRupeesPlain(balance.displayAmount), boxX + boxWidth - 14, summaryY + 72, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(balance.label, boxX + boxWidth - 14, summaryY + 86, { align: "right" });

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("Generated by Hisab · Your business. Your Hisab.", margin, pageHeight - 24);

  return doc.output("blob");
}

const PAYMENT_LABELS: Record<string, string> = {
  cash: "Cash",
  upi: "UPI",
  bank: "Bank",
  card: "Card",
  credit: "Credit",
  other: "Other",
  settlement: "Settlement",
};

export function statementFilename(entity: Entity): string {
  return `${entity.name.replace(/\s+/g, "_")}_statement_${new Date().toISOString().slice(0, 10)}.pdf`;
}
